using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Forms;

// Jay Jay if youre reading this then here is the checklist.

//TODO LIST: 
// 1.- Add all needed tabs to the launcher [not done]
// 2.- Add a loading screen [havent even started, oof]
// 3.- Tidy up the UI and MAYBE optimize the code? [idk why i should optimize it i just feel like its not organized]

// 4.- Figure out how to do a Json to catalog. [havent even started]
// what I mean by this is like it checks a folder in the Auroria Folder/Data/Catalog
// and it finds a json file with a whole bunch of information and stuff.
// actually it would just be better if you talked to me about it on discord.

// 5.- Add live banner. Basically it grabs the text from https://sites.google.com/view/auroriainfopnl/home?authuser=1 and
// converts it to the Banner text. [havent even started]

// thats just all the stuff we need to do for now, if you have any questions about anything then just ask me on discord. -Lucas
// Oh and if you struggle on something thats aye okay just let me do it dont worry about it :D
namespace Auroria.NT
{
    public partial class AurNTBase : Form
    {
        public AurNTBase()
        {   // Gonna be adding a loading screen soon. Which means we may need a bit of a delay here? I will explain
            // if needed. -Lucas
            InitializeComponent();
        }

        private void AddFolder(TreeNode parentNode, string folderPath) // Populates the Map Tree view.
        {
            foreach (string folder in Directory.GetDirectories(folderPath))
            {
                TreeNode folderNode =
                    parentNode.Nodes.Add(Path.GetFileName(folder));

                AddFolder(folderNode, folder);
            }

            foreach (string file in Directory.GetFiles(folderPath, "*.rbxl")) // Jay can you make it so that it can show .gz2 and .gz files too pls?
            {
                parentNode.Nodes.Add(Path.GetFileName(file));
            }
        }

        private void PlayPage_Click(object sender, EventArgs e)
        {

        }

        private void AurNTBase_Load(object sender, EventArgs e)
        {
            MessageBox.Show(
                "Hello, Welcome to Auroria .NT Core!",
                "Auroria .NT",
                MessageBoxButtons.OKCancel, MessageBoxIcon.Information
            );

            MessageBox.Show(
                "Note that this is a work in progress edition of Auroria, things may not work as expected!",
                "Auroria .NT",
                MessageBoxButtons.OK, MessageBoxIcon.Information
            );

            string NrmlBanner = "Data\\Banners\\BannerLongNT.png";
            string mapsFolder = "Maps";
            string ChckMapDirectory = @"Maps";

            BackgroundBox.ImageLocation = NrmlBanner;

            if (!Directory.Exists(ChckMapDirectory))
            {
                MessageBox.Show("Either the Maps folder doesn't exist or Auroria cannot find it!", "Auroria .NT", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return; // PRAY That it just doesn't exist. If Auroria can't find it, something has gone horribly wrong.
                // Thankfully thats a super low chance right?
            }

                foreach (string folder in Directory.GetDirectories(mapsFolder))
                {
                    TreeNode folderNode =
                        MapsTree.Nodes.Add(Path.GetFileName(folder));

                    AddFolder(folderNode, folder);
                }
        }

        // Idk why all of this useless stuff is here, it was auto generated by VS but im not gonna
        // remove it because itll cause errors. Besides if it aint broke dont fix it. -Lucas
        private void MapsLbl_Click(object sender, EventArgs e)
        {

        }

        private void MapsList_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void MapsTree_AfterSelect(object sender, TreeViewEventArgs e)
        {

        }

        private void JoinBtn_click(object sender, EventArgs e)
        {

        }

        private void HostBtn_Click(object sender, EventArgs e)
        {

        }

        private void MOTDLabel(object sender, EventArgs e)
        {

        }

        private void PlayerNameBox_TextChanged(object sender, EventArgs e)
        {

        }

        private void ClientList_SelectedIndexChanged(object sender, EventArgs e)
        {
            string errThumbnail = "Data\\ClientThmbnl\\ErrOrCstm\\ClientErCstm.png";

            if (ClientList.SelectedItem != null)
            {
                string selectedClient = ClientList.SelectedItem.ToString();
                // Perform actions based on the selected client

                if (selectedClient == "2007S") // <-- Future note to self since im a C# noob: DONT ADD A ; HERE -Lucas
                {
                    ClientPictureBox.ImageLocation = "Data\\ClientThmbnl\\2007S\\2007Img.png";
                    ClientInfoBox.Text = "A recreation of the February 2007 Client!";
                    MessageBox.Show("Note: 2007S May not be a perfectly accurate recreation!", "Auroria .NT", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }

                else // Remove this when other clients have been officially added to the launcher. This is just a placeholder cuz im a chud..
                {
                    ClientPictureBox.ImageLocation = errThumbnail;
                    ClientInfoBox.Text = "Client is either custom or Non-Functional!";
                    MessageBox.Show("NF = Non Functional! This Client has NOT been added yet!", "Auroria .NT", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
        }

        private void ClientInfoBox_TextChanged(object sender, EventArgs e)
        {

        }

        private void ClientPictureBox_Click(object sender, EventArgs e)
        {

        }
    }
}
